service: aws-form-send-serverless-lambda

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, self:custom.defaultStage}
  # profile: ${self:custom.profiles.${sls:stage}}
  region: us-east-1
  # memorySize: 512

custom:
  defaultStage: development
  dotenv:
    basePath: src/common/envs/
  # profiles:
  #   dev: devProfile
  #   prod: prodProfile

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: / # this matches the base path
      - http:
          method: ANY
          path: '{proxy+}' # this matches any path, the token 'any' doesn't mean anything special
