service: aws-form-send-serverless-lambda

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, self:custom.defaultStage}
  # profile: ${self:custom.profiles.${sls:stage}}
  region: us-east-1
  memorySize: 512

  environment:
    NODE_ENV: ${sls:stage}
    GOOGLE_FORM_ID: ${file(./serverless-config/${opt:stage, 'dev'}.config.json):GOOGLE_FORM_ID}

custom:
  defaultStage: dev
  # profiles:
  #   dev: devProfile
  #   prod: prodProfile

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
